"""Add date column to student_attendance

Revision ID: 8c90ce57381f
Revises: b033ff7914c8
Create Date: 2025-10-23 15:37:28.547442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c90ce57381f'
down_revision = 'b033ff7914c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_attendance_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attendance_date'))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
