"""Initial migration

Revision ID: c5cd63bbf457
Revises: 
Create Date: 2025-10-06 11:48:13.048565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cd63bbf457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_uuid'), ['uuid'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='user_roles'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    op.create_table('biometrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint_template', sa.LargeBinary(), nullable=True),
    sa.Column('face_template', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biometrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biometrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biometrics_user_id'), ['user_id'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('last_password_reset_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('staff_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_attendance_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendance_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendance_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendance_user_id'), ['user_id'], unique=False)

    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_attendance_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_status'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_method'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_created_at'))

    op.drop_table('student_attendance')
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_attendance_status'))
        batch_op.drop_index(batch_op.f('ix_staff_attendance_method'))
        batch_op.drop_index(batch_op.f('ix_staff_attendance_created_at'))

    op.drop_table('staff_attendance')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_user_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('biometrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biometrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_biometrics_created_at'))

    op.drop_table('biometrics')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_department'))

    op.drop_table('users')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_uuid'))
        batch_op.drop_index(batch_op.f('ix_students_phone'))
        batch_op.drop_index(batch_op.f('ix_students_email'))
        batch_op.drop_index(batch_op.f('ix_students_department'))
        batch_op.drop_index(batch_op.f('ix_students_created_at'))

    op.drop_table('students')
    # ### end Alembic commands ###
